#!/bin/bash -e

SCRIPT_PATH="$(dirname -- "${BASH_SOURCE[0]}")"
cd $SCRIPT_PATH/..

cmake -B build-linux \
	--no-warn-unused-cli \
	-DCMAKE_TOOLCHAIN_FILE=CMake-linux.cmake \
	-DCMAKE_BUILD_TYPE=Release

cmake --build build-linux

echo && echo "Running..."
./build-linux/hello_world
