#!/bin/bash -e

SCRIPT_PATH="$(dirname -- "${BASH_SOURCE[0]}")"
cd $SCRIPT_PATH/..

cmake -B build-windows \
	--no-warn-unused-cli \
	-DCMAKE_TOOLCHAIN_FILE=CMake-mingw-w64.cmake \
	-DCMAKE_BUILD_TYPE=Release

cmake --build build-windows

echo && echo "Running..."
wine ./build-windows/hello_world.exe
