#!/bin/bash

if [[ ! -v PROJECT_BASE ]]; then
	echo "PROJECT_BASE is not set, please set it" && exit 1
fi

cd $PROJECT_BASE

clear() {
	SUBDIR="$1"
	(
		cd $SUBDIR

		directories=($(find . -mindepth 1 -maxdepth 1 -not -path '*/.*' -type d -printf '%f\n'))
		directories=($(echo "${directories[@]}" | tr ' ' '\n' | sort))
		echo "Start the cleaning $SUBDIR..."

		for directory in "${directories[@]}"; do
			script="$directory/.scripts/clean"
			if [ -f "$script" ]; then
				echo "Running $script" && "$script"
			fi
		done
		echo
	)
}

clear 1_c++

echo "Done"
